# file: lxc-containers.yml
- name: "Configure LXC Container(s): Spark"
  hosts: lxc-spark
  roles:
    - lxc-spark
  tags: lxc-spark

- name: "Configure LXC Container(s): MongoDB"
  hosts: lxc-mongodb
  roles:
    - lxc-mongodb
  tags: lxc-mongodb

- name: "Configure LXC Container(s): REDIS"
  hosts: lxc-redis
  roles:
    - lxc-redis
  tags: lxc-redis

- name: "Configure LXC Container(s): JUPYTER"
  hosts: lxc-jupyter
  roles:
    - lxc-jupyter
  tags: lxc-jupyter

#- name: "LXC Container(s): Hadoop Cluster"
#  hosts: lxc-hadoop-cluster
#  roles:
#    - lxc-hadoop-cluster


