# Create REDIS containers
- name: Create a started container
  lxc_container:
    name: redis1
    container_log: true
    state: started
    config: ~/.config/lxc/default.conf
    container_command: |
      sudo apt-get update
      sudo apt-get install -y openssh-server
      sudo apt-get install -y python
      useradd rramos
      mkdir -p /home/rramos/.ssh
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCwLmBOt0YBkp36ziO9qra4wwmWUW+QT+gEEDqtRY55hSK5FVmwSjT5Swjfy61sSHpqZ4aZ95vaa7Tjh6q7Pu33utWNf+6oMNPPtEHg1puYggWkmGkoHtF10qNiVV60k4+XaP+xIc8T2A6/KZ4PpCf6XOIPavH8GfQe4yPl1LM9YytnTaNiOzL7uhSn01k67Q4nWX+4mikiQuuSBj7TwodFkubGW++S7QNQMbE2H7kVt5vt/2THgD+t1dwiAn1Xlh1JVJqXf9G/h6Lhf1tQsundsU7naRp+lpNhwVUNbwHDT3juxB6JDP1E/OJWXkSmEHHL+joA0zLIxTaxZ6cWsBv rramos@buldozer" > /home/rramos/.ssh/authorized_keys
      chown -R rramos:rramos /home/rramos
      echo "rramos ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/rramos
      sudo usermod -s /bin/bash rramos
    template_options: -d ubuntu -r xenial -a amd64

