- name: "REDIS container Packages install"
  apt: name={{item}} state=installed
  become: yes
  with_items:
       - git
       - wget
       - redis-server
       - redis-tools
       - tree
  tags: lxc-redis-packages
